### ISSUE TITLE
Why did you put the ENV-Vars to the Build Script?

### ISSUE THREAD

**Issue by AleksCee** [philipparndt/miele-to-mqtt-gw#19]
\
--build-arg MIELE_CLIENT_ID=$MIELE_CLIENT_ID \
--build-arg MIELE_CLIENT_SECRET=$MIELE_CLIENT_SECRET \
--build-arg MIELE_PASSWORD=$MIELE_PASSWORD \
--build-arg MIELE_USERNAME=$MIELE_USERNAME \

Now there are errors when Building as befor.

**Comment by philipparndt** [comment]
The env variables are necessary to run the test cases against the real Miele API.
Maybe I should add another script to build without test cases.

I like to always run the test cases when building a release for docker hub.

**Comment by AleksCee** [comment]
Ok, after setting the ENV I get:

Failed tests:   test_device_list(de.rnd7.miele.api.MieleAPITest): expected:<1> but was:<2>

But in Produktion the Config works.

**Comment by AleksCee** [comment]
Oh I see - You have one device an I have 2 - to the Test ist very bad, or?

**Comment by AleksCee** [comment]
next fail where - I have no Dishwasher ;-)

final MieleDevice dishwasher = devices.iterator().next();
        assertEquals("G7560", dishwasher.getData()
                .getJSONObject("ident")
                .getJSONObject("deviceIdentLabel")
                .get("techType").toString());

**Comment by AleksCee** [comment]
After setting list to 2 devices and delete the assert for the dishwasher my Build was successfull.
The tests are to specific to your configuration, I think...

**Comment by philipparndt** [comment]
I've updated the test case and think about changing the build process. Building the java app in the docker container is significantly slower compared to just build it using a local Maven build or on GitHub. The Docker build could just download the released and tested build from GitHub instead of building it.

**Comment by AleksCee** [comment]
I like the way how it‘s work right now. I have learn many new stuff with your project. So for me it‘s ok now.
Thanks, Alex

**Comment by AleksCee** [comment]
Ah, and I Test the sse Mode. Seams to work fine right now. Cool new feature!!! Also the deduplicate is perfect!

**Comment by philipparndt** [comment]
> Ah, and I Test the sse Mode. Seams to work fine right now. Cool new feature!!! Also the deduplicate is perfect!

Thanks, I forgot to ask you whether or not you use the SSE mode. I have it in test now for about two days. It's really nice to get instant notifications, wish this would be available for Hue switches as well...

**Comment by AleksCee** [comment]
Yes, it‘s great!!! Hope the reconnect works fine if the internet or Miele server is offline for a moment.
But the first look at this new feature is perfect! Thanks a lot for it!
