### ISSUE TITLE
Where is the jar for the „only prod“ Docker-file?

### ISSUE THREAD

**Issue by AleksCee** [philipparndt/miele-to-mqtt-gw#24]
Hi,

with the new build Prozess and using only the Docker file in the root, where Dose the:

COPY src/de.rnd7.mieletomqtt/target/miele-to-mqtt-gw.jar .

come from?

Thanks, Alex

**Comment by AleksCee** [comment]
Another hint. I have build many times since yesterday and the online test fails some time. I think because the duplicate login with the same account? Perhaps an hint to stop the running docker while building was a good idea?

**Comment by philipparndt** [comment]
The jar has to be built using `mvn package` first. I changed this, as the resulting jar is platform-independent and can be used for all platform dependent docker containers (armv6, v7, ...)

Do you have any error messages for the failing test? Up to now, I did not have any issues logging in multiple times.

**Comment by AleksCee** [comment]
First the error was an ArrayIndexOutOfBoundsException - I think because of an concurrent access to the API by the running docker and the Build-Test. Because the second Build was fine after stopping the container.

The jar: I mean - sorry in German: Also das Docker File im root hat ja nur die Zeile mit dem COPY Befehlt aber dort ist ja kein Build gelaufen, der lief ja im Docker (Build-Image) daher war die Frage - wo bekommt man das JAR in dem Fall her?

Wenn ich den Build mache kopiert er ja sofort aus dem Build-Container in den Prod-Container aber wenn man jetzt nur das [Docker](https://github.com/philipparndt/miele-to-mqtt-gw/blob/master/Dockerfile)-File aus dem root-Ordern nutzt - ist in src/ ja kein JAR-File:

**Comment by philipparndt** [comment]
ArrayIndexOutOfBoundsException:
die kommt vermutlich wenn etwas beim login schief geht.
Da habe ich jetzt mal die Fehlermeldung verbessert, mal schauen ob da jetzt eine andere kommt ;)

Zum build:
um den container im root folder zu bauen, musst du vorher `mvn -B package verify --file src/pom.xml` ausführen.
Dafür brauchst du natürlich ein Java und Maven im Path. Daher auch noch das zweite Dockerfile im source folder.

Ich habe das geändert, damit die GitHub Action nur einmal das jar bauen muss und nicht pro Platform die selber Jar bauen muss.

**Comment by AleksCee** [comment]
Build: ja das habe ich alles auf dem NAS nicht. Daher fand ich den Docker-build Ansatz so charmant... :-)
Hast du Lust/Zeit dich etwas privat auszutauschen? Ich finde das Projekt was du da gebaut hast echt cool. Zum einen weil es genau das ist, was ich brauche. Aber zum anderen das ganze Maven Build-Krams im Docker. Evtl. könntest du mir da etwas Starthilfe geben das alles besser zu verstehen?

**Comment by philipparndt** [comment]
@AleksCee klar, meine Mail Adresse steht im Dockerfile ;)
