### ISSUE TITLE
Flaky test case

### ISSUE THREAD

**Issue by AleksCee** [philipparndt/miele-to-mqtt-gw#33]
First I have to Build 3 Times. First I got this:
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running de.rnd7.miele.api.MieleAPITest
[ERROR] Tests run: 4, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 17.958 s <<< FAILURE! - in de.rnd7.miele.api.MieleAPITest
[ERROR] testLogin(de.rnd7.miele.api.MieleAPITest)  Time elapsed: 10.171 s  <<< ERROR!
java.lang.RuntimeException: Error while fetching token
	at de.rnd7.miele.api.MieleAPITest.testLogin(MieleAPITest.java:19)
Caused by: java.io.IOException: Unexpected code: 401 during login (Unauthorized).
	at de.rnd7.miele.api.MieleAPITest.testLogin(MieleAPITest.java:19)

[ERROR] test_refresh_token(de.rnd7.miele.api.MieleAPITest)  Time elapsed: 0.182 s  <<< ERROR!
java.lang.RuntimeException: Error while fetching token
	at de.rnd7.miele.api.MieleAPITest.test_refresh_token(MieleAPITest.java:28)
Caused by: java.io.IOException: Unexpected code: 401 during login (Unauthorized).
	at de.rnd7.miele.api.MieleAPITest.test_refresh_token(MieleAPITest.java:28)

I stopped the running docker-container and build again and got this:
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running de.rnd7.miele.api.MieleAPITest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.399 s - in de.rnd7.miele.api.MieleAPITest
[INFO] Running de.rnd7.miele.api.MieleDeviceTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in de.rnd7.miele.api.MieleDeviceTest
[INFO] Running de.rnd7.miele.api.DurationParserTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in de.rnd7.miele.api.DurationParserTest
[INFO] Running de.rnd7.miele.api.SSEClientTest
  RROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.035 s <<< FAILURE! - in de.rnd7.miele.api.SSEClientTest
[ERROR] test_sse_reconnect(de.rnd7.miele.api.SSEClientTest)  Time elapsed: 5.556 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in de.rnd7.miele.api.SSEClientTest that uses java.util.List was not fulfilled within 5 seconds.
	at de.rnd7.miele.api.SSEClientTest.test_sse_reconnect(SSEClientTest.java:46)

the 3rd build runs without changes on my site - I think the 5 seconds is in some cases to short?

[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running de.rnd7.miele.api.MieleAPITest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.201 s - in de.rnd7.miele.api.MieleAPITest
[INFO] Running de.rnd7.miele.api.MieleDeviceTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in de.rnd7.miele.api.MieleDeviceTest
[INFO] Running de.rnd7.miele.api.DurationParserTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 s - in de.rnd7.miele.api.DurationParserTest
[INFO] Running de.rnd7.miele.api.SSEClientTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.731 s - in de.rnd7.miele.api.SSEClientTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0
[INFO] 

now it's fine.

**Comment by philipparndt** [comment]
Thanks for the feedback, I don't believe that changing the timeout will fix this.
I have to investigate more to figure out why this test case is flaky.

**Comment by philipparndt** [comment]
this test case is fixed. However, other test cases that are using the real API are depending on the Miele service availability.
In a future version, we should stub more most parts of the Miele API and use the real API only for a cyclic integration test.
