### ISSUE TITLE
Log grows very fast

### ISSUE THREAD

**Issue by AleksCee** [philipparndt/miele-to-mqtt-gw#5]
Hi,

because of the line:
`LOGGER.info("{} = {}", topic, valueString); `
The log grows very fast and the messages are not so interested in normal mode. Can you perhaps set the logger to debug mode and add an switch to the docker to set the logger-level? I think that only errors and the mqtt connect info is relevant in „produktion-mode“. 

What are you thinking about this?

Thanks, Alex

**Comment by philipparndt** [comment]
Hi @AleksCee 

I think this is a good idea. This info is not relevant during production.

**Comment by AleksCee** [comment]
Thanks for your quick fix but how can I now set the loglevel to info? The default seams to be debug and so nothing is change at the log growing.

**Comment by AleksCee** [comment]
I have try to modify the Dockerfile 
```
ENV APP_LOGLEVEL info
....
CMD java -Dorg.slf4j.simpleLogger.defaultLogLevel=${APP_LOGLEVEL:-info} -jar miele-to-mqtt-gw.jar /var/lib/miele-to-mqtt-gw/config.json
```

But also if the level is off the logs from every level were logged.

**Comment by philipparndt** [comment]
> I have try to modify the Dockerfile
> 
> ```
> ENV APP_LOGLEVEL info
> ....
> CMD java -Dorg.slf4j.simpleLogger.defaultLogLevel=${APP_LOGLEVEL:-info} -jar miele-to-mqtt-gw.jar /var/lib/miele-to-mqtt-gw/config.json
> ```
> 
> But also if the level is off the logs from every level were logged.

I've updated the docker file to this approach using a ENV for the logback.xml
