### ISSUE TITLE
Loglevel not working because of using ch.qos.logback.classic in the project

### ISSUE THREAD

**Issue by AleksCee** [philipparndt/miele-to-mqtt-gw#7]
Hi,

Thanks for the quick fix in #5 but because of the use of ch.qos.logback the loglevel env variable I try to set with the -D options is not work. The ch.qos.logback seams to use debug as a default in the classic Modul if it not found any config.

Can you make this use a config with configuration over the Docker env-variables? Because the fix in #5 have no effect to the log growing with using the ch.qos.logback module.

Thx, Alex

**Comment by philipparndt** [comment]
Hi,

Thanks for the info! I'll have a look at it!

**Comment by AleksCee** [comment]
With your merge to master with the new version - the log is quite for my now. 
Only 2 entries:

```
16:48:17.631 INFO  - Info enabled
16:48:17.643 INFO  - Connecting MQTT client

```

Thanks!

**Comment by philipparndt** [comment]
Hi @AleksCee thank you for letting me know 👍 and sorry for the long delay. I was very busy in the last weeks.

**Comment by AleksCee** [comment]
@philipparndt Ich mach mal eben auf Deutsch.... ich find‘s schon super das du das hier überhaupt bereit gestellt hast und so schnell auf meinen Wunsch eingegangen bist. Inzwischen ist auch der Trockner da und das Deinem Projekt konnte ich alles in Node Red einbinden. Lieben Dank und schöne Weihnachten für Dich!

**Comment by philipparndt** [comment]
Das freut mich zu hören :)
